CineGest/cinegest/Models/Tickets.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CineGest.Models
{
    public class Tickets
    {
        /// <summary>
        /// Id do bilhete
        /// </summary>
        [Key]
        [Display(Name = "# Bilhete")]
        public int Id { get; set; }

        /// <summary>
        /// Relaciona o bilhete com a sessão 
        /// </summary>
        [Required(ErrorMessage = "Este campo é de preenchimento obrigatório.")]
        [Display(Name = "# Sessão")]
        [ForeignKey(nameof(Session))]
        public int SessionFK { get; set; }
        public Sessions Session { get; set; }

        /// <summary>
        /// Relaciona o utilizador com a sessão do filme
        /// </summary>
        [Display(Name = "Utilizador")]
        [ForeignKey(nameof(User))]
        public int UserFK { get; set; }
        public Users User { get; set; }

        /// <summary>
        /// Lugar respetivo ao bilhete comprado para a sessão
        /// </summary>
        [Display(Name = "Lugar")]
        public int Seat { get; set; }
    }
}

CineGest/cinegest/Controllers/CinemasController.cs
using cinegest.Data;
using CineGest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace cinegest.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CinemasController : Controller
    {
        private readonly CinegestDB _context;

        public CinemasController(CinegestDB context)
        {
            _context = context;
        }

        /// <summary>
        /// GET: Cinemas
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cinemas.ToListAsync());
        }

        /// <summary>
        /// GET: Cinemas/Details/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                RedirectToAction(nameof(Index));
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                RedirectToAction(nameof(Index));
            }

            return View(cinema);
        }

        /// <summary>
        /// GET: Cinemas/Create
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: Cinemas/Create
        /// </summary>
        /// <param name="cinema"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Capacity,City,Location")] Cinemas cinema)
        {

            if (ModelState.IsValid)
            {
                if (_context.Cinemas.Where(c => c.Name == cinema.Name).Any())//verifica se existe algum cinema com o mesmo nome
                {
                    ViewData["message"] = "Já existe um cinema com o mesmo nome.";
                    return View(cinema);
                }
                //adiciona o utilizador
                _context.Add(cinema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var cinemas = await _context.Cinemas.FindAsync(id);
            if (cinemas == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(cinemas);
        }

        // POST: Cinemas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Capacity,City,Location")] Cinemas cinema)
        {
            if (id != cinema.Id)
            {
                RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (await _context.Sessions.Where(s => s.Movie.Id == id).AnyAsync())//verifica se o filme tem sessoes agendadas
                    {
                        ViewData["message"] = "Não é possivel alterar o cinema, tendo sessões agendadas para o mesmo.";
                        return View(cinema);
                    }

                    if (_context.Cinemas.Where(c => c.Name == cinema.Name && c.Id != cinema.Id).Any())//verifica se existe algum cinema com o mesmo nome
                    {
                        ViewData["message"] = "Já existe um cinema com o mesmo nome.";
                        return View(cinema);
                    }

                    _context.Update(cinema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemasExists(cinema.Id))
                    {
                        RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        RedirectToAction(nameof(Index));
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                RedirectToAction(nameof(Index));
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                RedirectToAction(nameof(Index));
            }

            return View(cinema);
        }

        // POST: Cinemas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var cinema = await _context.Cinemas.FindAsync(id);

            if (await _context.Sessions.Where(s => s.Cinema.Id == id).AnyAsync())//verifica se o cinema tem sessoes agendadas
            {
                ViewData["message"] = "Não é possivel apagar o cinema, tendo sessões agendadas para o mesmo.";
                return View(cinema);
            }

            _context.Cinemas.Remove(cinema);

            var sessions = await _context.Sessions.Where(s => s.Cinema == cinema).ToListAsync();//obtem a lista de sessoes no cinema
            foreach (var item in sessions) //apaga todas as sessions
            {
                _context.Sessions.Remove(item);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CinemasExists(int id)
        {
            return _context.Cinemas.Any(e => e.Id == id);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyName(string name)
        {
            if (_context.Cinemas.Where(c => c.Name == name).Any())
            {
                return Json($"Já existe um cinema com o mesmo nome.");
            }

            return Json(true);
        }
    }
}

CineGest/cinegest/Controllers/UsersController.cs
using cinegest.Areas.Identity.Pages.Account.Manage;
using cinegest.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace cinegest.Controllers
{
    public class UsersController : Controller
    {
        private readonly CinegestDB _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<DeletePersonalDataModel> _logger;
        public static IWebHostEnvironment _environment;

        public UsersController(CinegestDB context,
            SignInManager<ApplicationUser> signInManager,
            ILogger<DeletePersonalDataModel> logger,
            IWebHostEnvironment environment,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
            _environment = environment;
        }

        // GET: Users
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationUser = await _userManager.GetUserAsync(User);


            return View(await _context.User.Where(u => u.Id != applicationUser.User).ToListAsync());
        }

        // GET: Users/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            List<SelectListItem> list = new List<SelectListItem> {
                new SelectListItem() { Text = "User", Value = "User" },
                new SelectListItem() { Text = "Admin", Value = "Admin" }
            };

            ViewData["Roles"] = new SelectList(list, "Value", "Text");
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int Id, string Email, string Name, DateTime DoB, string Role, IFormFile Avatar)
        {
            var user = _context.User.Find(Id);
            if (user == null) return NotFound();

            if (ModelState.IsValid)
            {
                if (_context.User.Where(u => u.Email == Email && u.Id != Id).Any())//verifica se existe algum utilizador com o mesmo email
                {
                    ViewData["message"] = "Já existe um utilizador com o mesmo email.";
                    return View(_context.User.Find(Id));
                }

                try
                {
                    //verifica se o avatar mudou
                    if (Avatar == null)
                    { } //não muda a imagem
                    else if (!Avatar.ContentType.Contains("image")) //se o poster não fôr imagem usa-se a imagem default
                    {
                        //apaga a antiga imagem
                        if (user.Avatar != "default.png") System.IO.File.Delete(_environment.WebRootPath + "/images/users/" + user.Avatar);

                        //guarda a nova imagem
                        user.Avatar = "default.png";
                    }
                    else
                    { //update atualiza a imagem

                        //apaga o antigo poster excepto se for o poster default
                        if (user.Avatar != "default.png") System.IO.File.Delete(_environment.WebRootPath + "/images/users/" + user.Avatar);

                        Guid g;
                        g = Guid.NewGuid();

                        string extensao = Path.GetExtension(Avatar.FileName).ToLower();

                        // caminho do ficheiro 
                        user.Avatar = g.ToString() + extensao;

                        //guarda a imagem
                        using var fileStream = new FileStream(_environment.WebRootPath + "/images/users/" + g.ToString() + extensao, FileMode.Create);
                        await Avatar.CopyToAsync(fileStream);
                    }
                    //altera os dados do utilizador
                    user.Email = Email;
                    user.Name = Name;
                    user.DoB = DoB;
                    user.Role = Role;
                    _context.Update(user);

                    //altera os dados do application user
                    var netUser = await _context.Users.Where(u => u.User == Id).FirstOrDefaultAsync();
                    netUser.UserName = Email;
                    netUser.Email = Email;
                    netUser.Nome = Name;

                    //altera o cargo dependendo da opcao escolhida
                    var userRole = await _context.UserRoles.Where(uR => uR.UserId == netUser.Id).FirstOrDefaultAsync();
                    if (userRole.RoleId == "1" && Role == "User") //remove Admin e dá User
                    {
                        await _userManager.RemoveFromRoleAsync(netUser, "Admin");
                        await _userManager.AddToRoleAsync(netUser, "User");
                    }
                    else if (userRole.RoleId == "2" && Role == "Admin") // remove User e dá Admin
                    {
                        await _userManager.RemoveFromRoleAsync(netUser, "User");
                        await _userManager.AddToRoleAsync(netUser, "Admin");
                    }
                    await _userManager.UpdateAsync(netUser);  //edita o application user com os novos dados

                    _context.Update(userRole);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            List<SelectListItem> list = new List<SelectListItem> {
                new SelectListItem() { Text = "User", Value = "User" },
                new SelectListItem() { Text = "Admin", Value = "Admin" }
            };

            ViewData["Roles"] = new SelectList(list, "Value", "Text");
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var users = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.Where(u => u.User == id).FirstOrDefaultAsync();

            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{user.Id}'.");
            }

            //necessario ativar o bloqueio para apagar o utilizador, o utilizador e apagado quando voltar a fazer login
            await _userManager.SetLockoutEnabledAsync(user, true); //ativa o bloqueio
            await _userManager.SetLockoutEndDateAsync(user, DateTime.Now.AddYears(9)); //data de bloqueio

            return Redirect("~/");
        }

        private bool UsersExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }

    }
}

CineGest/cinegest/Views/Tickets/Delete.cshtml
@model CineGest.Models.Tickets

@{
    ViewData["Title"] = "Apagar Bilhete";
}

<h2>Apagar Bilhete</h2>

<p>Tem acerteza que quer apagar este registo?</p>
<div class="ml-3">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Session.Cinema.Name)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.Session.Cinema.Id">
                @Html.DisplayFor(model => model.Session.Cinema.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Session.Movie.Name)

        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Session.Movie.Id">
                @Html.DisplayFor(model => model.Session.Movie.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Users" asp-action="Details" asp-route-id="@Model.User.Id">
                @Html.DisplayFor(model => model.User.Email)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Seat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Seat)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à tabela</a>
    </form>

    <p class="text-warning mt-2">@ViewBag.message</p>

</div>

CineGest/cinegest/Views/Tickets/Index.cshtml
@model IEnumerable<CineGest.Models.Tickets>

@{
    ViewData["Title"] = "Bilhetes";
}

<h1>Bilhetes</h1>

<table class="table text-center">
    <thead>
        <tr>
            <th>
                Email
            </th>
            <th>
                Filme
            </th>
            <th>
                Cinema
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Cinema.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Cinema.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seat)
            </th>
            <th>
                Opções
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Users" asp-action="Details" asp-route-id="@item.UserFK">
                        @Html.DisplayFor(modelItem => item.User.Email)
                    </a>
                </td>
                <td>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@item.Session.MovieFK">
                        @Html.DisplayFor(modelItem => item.Session.Movie.Name)
                    </a>
                </td>
                <td>
                    <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@item.Session.CinemaFK">
                        @Html.DisplayFor(modelItem => item.Session.Cinema.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Cinema.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Cinema.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.End)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seat)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" title="Apagar"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

CineGest/cinegest/Views/Tickets/MyTickets.cshtml
@model IEnumerable<CineGest.Models.Tickets>

@{
    ViewData["Title"] = "Bilhetes";
}

<h1>Bilhetes</h1>

<table class="table mt-3 text-center">
    <thead>
        <tr>
            <th>
                Filme
            </th>
            <th>
                Cinema
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Cinema.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Cinema.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Session.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seat)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@item.Session.MovieFK">
                        @Html.DisplayFor(modelItem => item.Session.Movie.Name)
                    </a>
                </td>
                <td>
                    <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@item.Session.CinemaFK">
                        @Html.DisplayFor(modelItem => item.Session.Cinema.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Cinema.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Cinema.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Session.End)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seat)
                </td>
            </tr>
        }
    </tbody>
</table>